{
  "file_hash": "9eb7911f302275e8441416c43db818ba",
  "file_size": 217193,
  "pe_scanner": {
    "return_code": 1,
    "stdout": "",
    "stderr": "C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\sklearn\\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.6.1 when using version 1.4.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:\nhttps://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations\n  warnings.warn(\nC:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\sklearn\\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.6.1 when using version 1.4.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:\nhttps://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations\n  warnings.warn(\nTraceback (most recent call last):\n  File \"C:\\Users\\jacks\\Downloads\\bobcat labs\\leviathan\\FileGuardian\\Extract\\PE_main.py\", line 193, in <module>\n    data = extract_infos(sys.argv[1])\n  File \"C:\\Users\\jacks\\Downloads\\bobcat labs\\leviathan\\FileGuardian\\Extract\\PE_main.py\", line 81, in extract_infos\n    pe = pefile.PE(fpath)\n  File \"C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\pefile.py\", line 2895, in __init__\n    self.__parse__(name, data, fast_load)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\pefile.py\", line 3031, in __parse__\n    raise PEFormatError(\"DOS Header magic not found.\")\npefile.PEFormatError: 'DOS Header magic not found.'"
  },
  "document_scanner": {
    "return_code": 0,
    "stdout": "{\"is_malicious\": true, \"message\": \"Document contains suspicious content\", \"details\": {\"findings\": [{\"pattern\": \"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}\", \"match\": \"quickreliefpestcontrol@gmail.com\", \"position\": 140}, {\"pattern\": \"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}\", \"match\": \"iefpestcontrol@gmail.com\", \"position\": 2979}, {\"pattern\": \"(?i)(password|login|username|admin|root|system)\", \"match\": \"system\", \"position\": 1538}], \"file_type\": \"PDF\"}}",
    "stderr": ""
  },
  "flask_scan": {
    "return_code": 1,
    "stdout": "",
    "stderr": "Traceback (most recent call last):\n  File \"<string>\", line 4, in <module>\n    from app import run_local_file_scan\n  File \"C:\\Users\\jacks\\Downloads\\bobcat labs\\leviathan\\FileGuardian\\app.py\", line 23, in <module>\n    load_dotenv()\n    ~~~~~~~~~~~^^\n  File \"C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\dotenv\\main.py\", line 362, in load_dotenv\n    return dotenv.set_as_environment_variables()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\dotenv\\main.py\", line 93, in set_as_environment_variables\n    if not self.dict():\n           ~~~~~~~~~^^\n  File \"C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\dotenv\\main.py\", line 76, in dict\n    resolve_variables(raw_values, override=self.override)\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\dotenv\\main.py\", line 239, in resolve_variables\n    for name, value in values:\n                       ^^^^^^\n  File \"C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\dotenv\\main.py\", line 85, in parse\n    for mapping in with_warn_for_invalid_lines(parse_stream(stream)):\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\dotenv\\main.py\", line 25, in with_warn_for_invalid_lines\n    for mapping in mappings:\n                   ^^^^^^^^\n  File \"C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\dotenv\\parser.py\", line 173, in parse_stream\n    reader = Reader(stream)\n  File \"C:\\Users\\jacks\\AppData\\Roaming\\Python\\Python313\\site-packages\\dotenv\\parser.py\", line 64, in __init__\n    self.string = stream.read()\n                  ~~~~~~~~~~~^^\n  File \"<frozen codecs>\", line 325, in decode\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte"
  }
}